language: python
python:
  - "2.6"
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
before_install:
  - "sudo apt-get install python-dev"
install:
  - pip install -r requirements.txt
script:
  - python setup.py test
